<a href="https://colab.research.google.com/github/bahing-rai/ai_foundation/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import random

# set random seed for reproducibility
np.random.seed(42)

# generate data
num_rows = 100
data = {
    'User ID' : range(1, num_rows + 1),
    'Gender' : [random.choice(['Male','Female']) for _ in range(num_rows)],
    'Age' : [random.randint(18, 65) for _ in range(num_rows)],
    'Estimated Salary' : np.random.randint(20000, 200000, num_rows),
    'Purchased' : np.random.randint(0, 2, num_rows)
}

# create dataframe
df = pd.DataFrame(data)

In [4]:
display(df)

User ID  Gender  Age  Estimated Salary  Purchased
0         1    Male   47            141958          0
1         2  Female   62            166867          0
2         3    Male   34            151932          1
3         4  Female   39            123694          0
4         5    Male   31            139879          1
..      ...     ...  ...               ...        ...
95       96  Female   27             59504          0
96       97  Female   55            184231          0
97       98    Male   53             33986          1
98       99  Female   51             81858          0
99      100  Female   64            149312          1

[100 rows x 5 columns]

In [5]:
df.to_csv('dataset.csv', index = False)

In [6]:
# import the dataset
df = pd.read_csv('dataset.csv')
df.head(5)

User ID  Gender  Age  Estimated Salary  Purchased
0        1    Male   47            141958          0
1        2  Female   62            166867          0
2        3    Male   34            151932          1
3        4  Female   39            123694          0
4        5    Male   31            139879          1

### Steps :
- Data Preprocessing
- Fitting KNN to the training set
- Prediciting the result
- Test accuracy of the result
- Visualise the result


In [7]:
# importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [8]:
dataset = pd.read_csv('dataset.csv')

In [9]:
dataset

User ID  Gender  Age  Estimated Salary  Purchased
0         1    Male   47            141958          0
1         2  Female   62            166867          0
2         3    Male   34            151932          1
3         4  Female   39            123694          0
4         5    Male   31            139879          1
..      ...     ...  ...               ...        ...
95       96  Female   27             59504          0
96       97  Female   55            184231          0
97       98    Male   53             33986          1
98       99  Female   51             81858          0
99      100  Female   64            149312          1

[100 rows x 5 columns]

In [17]:
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

In [14]:
display(X)

array([[    47, 141958],
       [    62, 166867],
       [    34, 151932],
       [    39, 123694],
       [    31, 139879],
       [    43, 130268],
       [    50,  74886],
       [    24, 157337],
       [    32, 188266],
       [    57, 107498],
       [    42, 132727],
       [    23, 146324],
       [    35, 195203],
       [    21,  36023],
       [    65,  61090],
       [    20,  87221],
       [    27,  84820],
       [    40,  20769],
       [    58,  79735],
       [    39,  84925],
       [    61,  25311],
       [    20, 123355],
       [    48, 105305],
       [    33, 179765],
       [    33, 150608],
       [    64, 176730],
       [    39, 104478],
       [    47, 142537],
       [    22, 169503],
       [    39, 150523],
       [    38,  22747],
       [    63, 143855],
       [    62,  85725],
       [    44, 149981],
       [    25, 104654],
       [    27, 186845],
       [    49, 139346],
       [    48,  87435],
       [    18,  76886],
       [    62,  86803],


In [16]:
# splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [19]:
# feature scaling
from sklearn.preprocessing import StandardScaler
st_x = StandardScaler()
X_train = st_x.fit_transform(X_train)
X_test = st_x.transform(X_test)


In [20]:
X_test

array([[-0.21676418,  0.01977194],
       [ 0.13427093,  0.58579442],
       [-0.56779929,  0.90700293],
       [-1.69111163,  0.76539448],
       [ 0.6959271 , -0.52031828],
       [ 0.97675519,  1.79191553],
       [-1.05924844, -0.34776687],
       [-1.05924844,  0.14894712],
       [-0.70821333,  1.32997731],
       [-1.05924844, -0.82109134],
       [-0.14655716,  0.68716768],
       [-1.34007652,  0.76571232],
       [-1.62090461, -0.01163843],
       [-1.48049057, -1.26010745],
       [-1.2698695 ,  1.00805834],
       [-0.2869712 , -1.50832422],
       [ 0.41509902,  0.03523408],
       [-0.63800631,  0.88224856],
       [ 0.13427093,  0.87052576],
       [-0.70821333,  1.58632713]])

Fitting K-NN classifier to the Training data : Now we will fit the K-NN classifier to thge training data. To do this we will import the KNeighboursClassifier class of Sklearn Neighbors library. After importing the class, we will create the Classifier object of the class. The Parameter of this class will be


    n_neighbors : To define the required neighbors of the algorithm. Usually, it takes 5.
    metric = 'minkwski' : This is the default parameter and it decides the distance between the points.
    p = 2 : It is equivalent to the standard Euclidean metric.     

In [21]:
# Fitting KNN classifier to the training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

Predicting the Test Result : To predict the test set result, we will create a y_pred vector as we did in Logistic Regression. Below is the code for it :

In [22]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0])