<a href="https://colab.research.google.com/github/bahing-rai/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Header H1


In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [11]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [12]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [13]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

#Multidimensional arrays

In [19]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
n = np.array([
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [25]:
n[:,2]=[0,1,2] #rows naherne, column 2 ko replace gara
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [29]:
np.random.rand(3)


array([0.4359949 , 0.02592623, 0.54966248])

In [54]:
np.random.seed(12)
np.random.randn(5, 2)

array([[ 0.47298583, -0.68142588],
       [ 0.2424395 , -1.70073563],
       [ 0.75314283, -1.53472134],
       [ 0.00512708, -0.12022767],
       [-0.80698188,  2.87181939]])

#Element-wise you can perform operation on entire arrays

In [56]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [57]:
b = (10 + (a * 2))
b

array([10, 12, 14, 16, 18])

#Comparison operations
##You can perfrom element-wise comparisons and create boolean arrays

In [58]:
a

array([0, 1, 2, 3, 4])

In [59]:
a >= 2

array([False, False,  True,  True,  True])

In [60]:
b

array([10, 12, 14, 16, 18])

In [61]:
a > b

array([False, False, False, False, False])

#Summarizing
##Numpy provides functions for summarizing

In [62]:
a

array([0, 1, 2, 3, 4])

In [63]:
a.std() #standard deviation

1.4142135623730951

In [64]:
a.min()

0

In [65]:
a.max()

4

In [66]:
a.sum()

10